# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
pr: none

resources:
- repo: self

variables:
  imageRepositoryApi: 'hfp-analytics/api'
  imageRepositoryImporter: 'hfp-analytics/importer'
  containerRegistry: 'hfpanalyticsregistry.azurecr.io'
  dockerfilePathApi: '$(Build.SourcesDirectory)/Dockerfile.api_deploy'
  dockerfilePathImporter: '$(Build.SourcesDirectory)/Dockerfile.importer_deploy'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build api to container registry
      inputs:
        command: build
        repository: $(imageRepositoryApi)
        dockerfile: $(dockerfilePathApi)
        containerRegistry: Azure Container Registry Connection # Service connection created in Azure with this name
        # imageTag (dev/test/prod): a pipeline variable
        tags: |
          $(imageTag)
        arguments: '--build-arg BUILD_VERSION=$(build.buildNumber)'
    - task: Docker@2
      displayName: Push api to container registry
      inputs:
        command: push
        repository: $(imageRepositoryApi)
        dockerfile: $(dockerfilePathApi)
        containerRegistry: Azure Container Registry Connection # Service connection created in Azure with this name
        # imageTag (dev/test/prod): a pipeline variable
        tags: |
          $(imageTag)

    - task: Docker@2
      displayName: Build importer to container registry
      inputs:
        command: build
        repository: $(imageRepositoryImporter)
        dockerfile: $(dockerfilePathImporter)
        containerRegistry: Azure Container Registry Connection # Service connection created in Azure with this name
        # imageTag (dev/test/prod): a pipeline variable
        tags: |
          $(imageTag)
        arguments: '--build-arg BUILD_VERSION=$(build.buildNumber)'

    - task: Docker@2
      displayName: Push importer to container registry
      inputs:
        command: push
        repository: $(imageRepositoryImporter)
        dockerfile: $(dockerfilePathImporter)
        containerRegistry: Azure Container Registry Connection # Service connection created in Azure with this name
        # imageTag (dev/test/prod): a pipeline variable
        tags: |
          $(imageTag)
