---
# TEST compose file for one-off services.
version: "3.8"
services:
  python:
    build: ./python
    restart: "no"
    env_file: .env
    volumes:
      - ./python/src:/code:ro
    command: python digitransit_import.py

networks:
  default:
    external: true
    name: stopcorr_nw
